### ISSUE TITLE
Unable to install on Windows (blocks orbit on Windows)

### ISSUE THREAD

**Issue by mateon1** [ipfs/go-ipfs-dep#7]
During build, npm throws an "Error: No binary available on os:windows"

Log, [npm-debug.log](https://ipfs.io/ipfs/QmVAG3QiPFGHMQV6cJ9LcKERGWzcwQ1Gae3nPofkyqf8Vd):

```
C:\Users\matin\orbit>npm install go-ipfs --save

> bufferutil@1.2.1 install C:\Users\matin\orbit\node_modules\bufferutil
> node-gyp rebuild


C:\Users\matin\orbit\node_modules\bufferutil>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  bufferutil.cc
  win_delay_load_hook.c
     Creating library C:\Users\matin\orbit\node_modules\bufferutil\build\Release\bufferutil.lib and object C:\Users\mat
  in\orbit\node_modules\bufferutil\build\Release\bufferutil.exp
  Generating code
  Finished generating code
  bufferutil.vcxproj -> C:\Users\matin\orbit\node_modules\bufferutil\build\Release\\bufferutil.node

> go-ipfs@0.3.11 install C:\Users\matin\orbit\node_modules\go-ipfs
> node install.js

C:\Users\matin\orbit\node_modules\go-ipfs\install.js:63
    throw new Error("no binary available for os:" + goenv.GOOS)
    ^

Error: no binary available for os:windows
    at checkPlatform (C:\Users\matin\orbit\node_modules\go-ipfs\install.js:63:11)
    at Object.<anonymous> (C:\Users\matin\orbit\node_modules\go-ipfs\install.js:12:1)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (node.js:348:7)
    at startup (node.js:140:9)
orbit@3.1.0 C:\Users\matin\orbit
`-- bufferutil@1.2.1

npm ERR! Windows_NT 10.0.14926
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "go-ipfs" "--save"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! code ELIFECYCLE

npm ERR! go-ipfs@0.3.11 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the go-ipfs@0.3.11 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the go-ipfs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs go-ipfs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls go-ipfs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\matin\orbit\npm-debug.log
```

**Comment by diasdavid** [comment]
Weird, thought this was fixed with https://github.com/diasdavid/go-ipfs-dep/pull/9
@edsilv can you take a look?

**Comment by edsilv** [comment]
@diasdavid This looks like a similar problem with https://github.com/ipfs/npm-go-ipfs
Not sure where/why that's being used instead of go-ipfs-dep... @haadcode ?

**Comment by haadcode** [comment]
Note that this issue was entered before #9 was merged.

@mateon1 do you still run into this problem with the latest version of go-ipfs-dep?

**Comment by diasdavid** [comment]
seems resolved now (working for everyone at least :))
